# Generated by Django 5.2 on 2025-04-22 19:37

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        (
            "import_export_extensions",
            "0009_alter_exportjob_data_file_alter_importjob_data_file",
        ),
    ]

    operations = [
        migrations.CreateModel(
            name="ExportJob",
            fields=[
                (
                    "exportjob_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="import_export_extensions.exportjob",
                    ),
                ),
            ],
            options={
                "abstract": False,
            },
            bases=("import_export_extensions.exportjob",),
        ),
    ]
