import uuid

from django.db import models
from django.utils.translation import gettext_lazy as _

from user.models import User
from import_export_extensions.models import ExportJob

class UserTask(models.Model):
    
    def _user_directory_path(instance, filename):
        return f"tasks/{uuid.uuid4()}/{filename}"
    
    class TaskStatus(models.TextChoices):
        """Task possible statuses.

        * STARTED:
            Task is just started, no task being done
        * PENDING:
            Task started, being processed
        * FAILURE:
            Task concluded with erros
        * SUCCESS:
            Task concluded successfully
        * REVOKED:
            Task revoked
        * RETRY:
            Task concluded with erros, therefore, passed by retry


        """

        STARTED = "STARTED", _("Started")
        PENDING = "PENDING", _("Pending")
        FAILURE = "FAILURE", _("Failure")
        SUCCESS = "SUCCESS", _("Success")
        REVOKED = "REVOKED", _("Revoked")
        RETRY = "RETRY", _("Retry")

    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='tasks')
    task_id = models.CharField(max_length=255, unique=True)
    task_name = models.CharField(max_length=255)
    label = models.TextField()
    status = models.CharField(max_length=50, choices=TaskStatus.choices, default=TaskStatus.PENDING)
    result = models.JSONField(blank=True, null=True)
    data_file = models.FileField(
        upload_to=_user_directory_path,
        null=True,
        blank=True,
        verbose_name=_("Data file"),
        help_text=_('Raw file or export generated by the task')
    )
    concluded_at = models.DateTimeField(null=True)
    created_at = models.DateTimeField(editable=False, auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)

    def __str__(self):
        return f"{self.task_name} ({self.task_id}) - {self.status}"
