import uuid
import logging


from django.db import models
from django.utils.translation import gettext_lazy as _
from django.utils import timezone

from user.models import User
from import_export_extensions.models import ExportJob

logger = logging.getLogger(__name__)

class UserTask(models.Model):
    
    def _user_directory_path(instance, filename):
        return f"tasks/{uuid.uuid4()}/{filename}"
    
    @property
    def is_revoked(self) -> bool:
        return True if self.status == self.TaskStatus.REVOKED else False
    
    def mark_revoked(self):
        """Mark task as revoked"""
        self.status = self.TaskStatus.REVOKED
        self.concluded_at = timezone.now()
        self.save()
        logger.info(f"✓ Task {self.task_id} marked as revoked")
    
    class TaskStatus(models.TextChoices):
        """Task possible statuses.

        * STARTED:
            Task is just started, no task being done
        * PENDING:
            Task started, being processed
        * FAILURE:
            Task concluded with erros
        * SUCCESS:
            Task concluded successfully
        * REVOKED:
            Task revoked
        * RETRY:
            Task concluded with erros, therefore, passed by retry


        """

        STARTED = "STARTED", _("Started")
        PENDING = "PENDING", _("Pending")
        FAILURE = "FAILURE", _("Failure")
        SUCCESS = "SUCCESS", _("Success")
        REVOKED = "REVOKED", _("Revoked")
        RETRY = "RETRY", _("Retry")

    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='tasks')
    task_id = models.UUIDField(default=uuid.uuid4, unique=True)
    label = models.TextField()
    status = models.CharField(max_length=50, choices=TaskStatus.choices, default=TaskStatus.PENDING)
    result = models.JSONField(blank=True, null=True)
    data_file = models.FileField(
        upload_to=_user_directory_path,
        null=True,
        blank=True,
        verbose_name=_("Data file"),
        help_text=_('Raw file or export generated by the task')
    )
    export_job = models.ForeignKey(
        ExportJob,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        help_text=_('Reference to the ExportJob associated with this task, if applicable')
    )
    concluded_at = models.DateTimeField(null=True)
    created_at = models.DateTimeField(editable=False, auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)
    traceback = models.TextField(
        blank=True,
        default=str,
        verbose_name=_("Traceback"),
        help_text=_("Python traceback in case of import/export error"),
    )
    error_message = models.CharField(
        max_length=128,
        blank=True,
        default=str,
        verbose_name=_("Error message"),
        help_text=_("Python error message in case of import/export error"),
    )

    def __str__(self):
        return f"({self.task_id}) - {self.status}"
