import uuid
import logging


from django.db import models
from django.utils.translation import gettext_lazy as _
from django.utils import timezone

from user.models import User
from import_export_extensions.models import ExportJob

logger = logging.getLogger(__name__)

class UserTask(models.Model):
    
    def _user_directory_path(instance, filename):
        return f"tasks/{uuid.uuid4()}/{filename}"
    
    @property
    def is_revoked(self) -> bool:
        return True if self.status == self.TaskStatus.REVOKED else False
    
    def mark_revoked(self):
        """Mark task as revoked"""
        self.status = self.TaskStatus.REVOKED
        self.concluded_at = timezone.now()
        self.save()
        logger.info(f"✓ Task {self.task_id} marked as revoked")
    
    class TaskStatus(models.TextChoices):
        """Task possible statuses.

        * STARTED:
            Task is just started, no task being done
        * PENDING:
            Task started, being processed
        * FAILURE:
            Task concluded with erros
        * SUCCESS:
            Task concluded successfully
        * REVOKED:
            Task revoked
        * RETRY:
            Task concluded with erros, therefore, passed by retry


        """

        STARTED = "STARTED", _("Started")
        PENDING = "PENDING", _("Pending")
        FAILURE = "FAILURE", _("Failure")
        SUCCESS = "SUCCESS", _("Success")
        REVOKED = "REVOKED", _("Revoked")
        RETRY = "RETRY", _("Retry")

    user = models.ForeignKey(User, on_delete=models.CASCADE, related_name='tasks')
    task_id = models.UUIDField(default=uuid.uuid4, unique=True)
    label = models.TextField()
    status = models.CharField(max_length=50, choices=TaskStatus.choices, default=TaskStatus.PENDING)
    result = models.JSONField(blank=True, null=True)
    data_file = models.FileField(
        upload_to=_user_directory_path,
        null=True,
        blank=True,
        verbose_name=_("Data file"),
        help_text=_('Raw file or export generated by the task')
    )
    export_job = models.ForeignKey(
        ExportJob,
        on_delete=models.SET_NULL,
        null=True,
        blank=True,
        help_text=_('Reference to the ExportJob associated with this task, if applicable')
    )
    concluded_at = models.DateTimeField(null=True)
    created_at = models.DateTimeField(editable=False, auto_now_add=True)
    update_at = models.DateTimeField(auto_now=True)
    traceback = models.TextField(
        blank=True,
        default=str,
        verbose_name=_("Traceback"),
        help_text=_("Python traceback in case of import/export error"),
    )
    error_message = models.CharField(
        max_length=128,
        blank=True,
        default=str,
        verbose_name=_("Error message"),
        help_text=_("Python error message in case of import/export error"),
    )

    def __str__(self):
        return f"({self.task_id}) - {self.status}"


class TaskRetryTracker(models.Model):
    """
    Centralized retry tracking across error handler invocations.
    
    Problem solved:
    - Error handler is called as a new task with NEW task_id
    - self.request.retries resets to 0 in each error handler invocation
    - We lose track of actual retry count
    
    Solution:
    - Use ONE database record per workflow (keyed by parent_task_id)
    - Increment counter on each error handler invocation
    - Check counter to know when to give up
    
    This survives error handler task_id changes because it's in the database.
    """
    
    parent_task_id = models.UUIDField(unique=True, db_index=True, editable=False)
    retry_count = models.IntegerField(default=0)
    max_retries = models.IntegerField(default=5)
    created_at = models.DateTimeField(auto_now_add=True)
    updated_at = models.DateTimeField(auto_now=True)
    
    class Meta:
        db_table = 'tasks_task_retry_tracker'
        indexes = [
            models.Index(fields=['parent_task_id']),
        ]
    
    @classmethod
    def increment_and_check(cls, parent_task_id, max_retries=5):
        """
        Increment retry count and check if max exceeded.
        
        This is the core method used by error handlers.
        Atomically increments counter in database.
        
        Args:
            parent_task_id: UUID of parent workflow task
            max_retries: Max allowed retries (usually 5)
        
        Returns:
            tuple: (retry_count_after_increment, max_exceeded)
                Example: (1, False) on first call
                Example: (5, True) on fifth call
        
        Usage:
            retry_count, max_exceeded = TaskRetryTracker.increment_and_check(
                parent_task_id,
                max_retries=5
            )
            
            if max_exceeded:
                # Don't retry, route to DLQ
                return {'status': 'failed_max_retries'}
            else:
                # Schedule retry
                workflow.apply_async(...)
        """
        tracker, created = cls.objects.get_or_create(
            parent_task_id=parent_task_id,
            defaults={'max_retries': max_retries}
        )
        
        tracker.retry_count += 1
        tracker.save(update_fields=['retry_count', 'updated_at'])
        
        is_max_exceeded = tracker.retry_count >= max_retries
        
        return tracker.retry_count, is_max_exceeded
    
    @classmethod
    def get_retry_count(cls, parent_task_id):
        """Get current retry count for a task."""
        try:
            return cls.objects.get(parent_task_id=parent_task_id).retry_count
        except cls.DoesNotExist:
            return 0
    
    @classmethod
    def cleanup(cls, parent_task_id):
        """
        Delete tracker after task completed successfully.
        
        Called when task completes or exhausts retries.
        Keeps database clean of old records.
        """
        cls.objects.filter(parent_task_id=parent_task_id).delete()
    
    def __str__(self):
        return f"TaskRetry({self.parent_task_id}, {self.retry_count}/{self.max_retries})"
    
    def __repr__(self):
        return f"<TaskRetryTracker: {self.parent_task_id} ({self.retry_count}/{self.max_retries})>"