# Generated by Django 5.2 on 2025-04-23 23:03

import tasks.models
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="usertask",
            name="data_file",
            field=models.FileField(
                blank=True,
                help_text="Raw file or export generated by the task",
                null=True,
                upload_to=tasks.models.UserTask._user_directory_path,
                verbose_name="Data file",
            ),
        ),
        migrations.AlterField(
            model_name="usertask",
            name="status",
            field=models.CharField(
                choices=[
                    ("STARTED", "Started"),
                    ("PENDING", "Pending"),
                    ("FAILURE", "Failure"),
                    ("SUCCESS", "Success"),
                    ("REVOKED", "Revoked"),
                    ("RETRY", "Retry"),
                ],
                default="PENDING",
                max_length=50,
            ),
        ),
    ]
