# Generated by Django 5.2 on 2025-04-25 18:53

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        (
            "import_export_extensions",
            "0009_alter_exportjob_data_file_alter_importjob_data_file",
        ),
        ("tasks", "0002_usertask_data_file_alter_usertask_status"),
    ]

    operations = [
        migrations.AddField(
            model_name="usertask",
            name="error_message",
            field=models.CharField(
                blank=True,
                default=str,
                help_text="Python error message in case of import/export error",
                max_length=128,
                verbose_name="Error message",
            ),
        ),
        migrations.AddField(
            model_name="usertask",
            name="export_job",
            field=models.ForeignKey(
                blank=True,
                help_text="Reference to the ExportJob associated with this task, if applicable",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="import_export_extensions.exportjob",
            ),
        ),
        migrations.AddField(
            model_name="usertask",
            name="traceback",
            field=models.TextField(
                blank=True,
                default=str,
                help_text="Python traceback in case of import/export error",
                verbose_name="Traceback",
            ),
        ),
    ]
