# Generated by Django 5.2 on 2025-04-23 23:13

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0002_usertask_data_file_alter_usertask_status"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usertask",
            name="export_task",
        ),
    ]
