# Generated by Django 5.2 on 2025-04-25 20:25

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0003_usertask_error_message_usertask_export_job_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="usertask",
            name="task_name",
        ),
    ]
