# Generated by Django 5.2 on 2025-04-27 01:29

import uuid
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tasks", "0004_remove_usertask_task_name"),
    ]

    operations = [
        migrations.AlterField(
            model_name="usertask",
            name="task_id",
            field=models.UUIDField(default=uuid.uuid4, unique=True),
        ),
    ]
