# Generated by Django 5.1 on 2024-11-26 01:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chemicals', '0007_literature_title_fulltext_search_idx'),
    ]

    operations = [
        migrations.AlterField(
            model_name='identifier',
            name='slug',
            field=models.TextField(blank=True, null=True),
        ),
    ]
