#!/bin/bash
#PBS -N pdf2chemicals_{{job_id}}
#PBS -l nodes={{node_name}}
#PBS -l walltime=72:00:00

# Go to working directory
cd $PBS_O_WORKDIR || { echo "Failed to change to PBS_O_WORKDIR"; exit 1; }

# Initialize Conda for bash
eval "$(/home/estevao/miniconda3/bin/conda shell.bash hook)"

# Enable Conda environment
conda activate {{conda_env}}

nvidia-smi
if [ $? -ne 0 ]; then
    echo "Error: GPU not available."
    exit 1
fi

# Verify that the environment was activated correctly
if [ $? -ne 0 ]; then
    echo "Error activating conda environment {{conda_env}}"
    exit 1
fi

# Check if Java is available
java -version
if [ $? -ne 0 ]; then
    echo "Error checking Java installation"
    exit 1
fi

# Run the main script
python {{pdf2chemicals_path}} {{json_prefix}} {{pdf_path}} {{output_dir}}

# Disable Conda environment
conda deactivate